README.md

Updating the readme:
- Provides assistance for the "I can't see jekyll compose commands" issue (https://github.com/jekyll/jekyll-compose/issues/4).
- Also adding a basic usage example to make clear the commands available. (I initially expected I would run `jekyll compose draft "My New Draft"`)

Updated readme with command help and examples

---

History.markdown
lib/jekyll-compose.rb
lib/jekyll-compose/file_mover.rb
lib/jekyll-compose/movement_arg_parser.rb
lib/jekyll/commands/post.rb
lib/jekyll/commands/publish.rb
lib/jekyll/commands/unpublish.rb
spec/publish_spec.rb
spec/unpublish_spec.rb

Unpublish command

---

lib/jekyll-compose/file_info.rb
spec/file_info_spec.rb

When titles have colons in them, it breaks the liquid template.
This encapsulates the titles in string literals if the user
wants a title with a colon in it.
Closes #38

Ensure colons do not break titles

---

lib/jekyll-compose/arg_parser.rb
lib/jekyll-compose/file_creator.rb
lib/jekyll-compose/file_mover.rb
lib/jekyll-compose/movement_arg_parser.rb
lib/jekyll/commands/draft.rb
lib/jekyll/commands/page.rb
lib/jekyll/commands/post.rb
lib/jekyll/commands/publish.rb
lib/jekyll/commands/unpublish.rb
spec/draft_spec.rb
spec/page_spec.rb
spec/post_spec.rb
spec/publish_spec.rb
spec/spec_helper.rb
spec/unpublish_spec.rb

Jekyll Compose assumes that the Jekyll code lives in the root directory, so if you have custom source set in your config, it won't respect that.
I've updated compose to load in configuration (adding both `--config` and `--source` options).

Allow Jekyll Source Directory

---

.rubocop.yml
Gemfile
jekyll-compose.gemspec
lib/jekyll-compose.rb
lib/jekyll-compose/arg_parser.rb
lib/jekyll-compose/file_creator.rb
lib/jekyll-compose/file_info.rb
lib/jekyll-compose/file_mover.rb
lib/jekyll-compose/movement_arg_parser.rb
lib/jekyll-compose/version.rb
lib/jekyll/commands/draft.rb
lib/jekyll/commands/page.rb
lib/jekyll/commands/post.rb
lib/jekyll/commands/publish.rb
lib/jekyll/commands/unpublish.rb
spec/draft_spec.rb
spec/file_info_spec.rb
spec/page_spec.rb
spec/post_spec.rb
spec/publish_spec.rb
spec/spec_helper.rb
spec/unpublish_spec.rb

This PR is the result of adding `inherit_gem:\n jekyll: .rubocop.yml` to `.rubocop.yml` and running `rubocop -a` so that this project follows Jekyll core's coding styles for consistency like other core plugins. This way, as Jekyll's Ruby style changes, so too will this project's.

Inherit Jekyll's rubocop config for consistency

---

lib/jekyll-compose/file_info.rb
lib/jekyll/commands/post.rb
spec/file_info_spec.rb
spec/post_spec.rb

Based on @xianny work (https://github.com/jekyll/jekyll-compose/pull/43). Added specs and comments from original pull request applied.
Closes #43

Add date to front matter when publish

---

lib/jekyll-compose/file_mover.rb
lib/jekyll-compose/movement_arg_parser.rb
lib/jekyll/commands/publish.rb
lib/jekyll/commands/unpublish.rb
spec/publish_spec.rb
spec/unpublish_spec.rb

The `post` command checks for overwriting files before creating a new post, and allows overwriting an existing post with `--force`.
Change `publish` and `unpublish` to behave the same way as `post`.
Had to teach `FileMover` about `force` and the `resource_type` had to be split into `from` and `to` for the error messages to be correct.
Also, `MovementArgParser` was modified to validate the force flag I think. I simplified it as there was some duplicate code with `ArgParser`. However I'd be happy to change this back and duplicate the code for force, especially if the change to `MovementArgParser` has some other side effects I haven't found yet.

Check if a file should be overwritten when publishing or unpublishing a post

---

README.md
lib/jekyll-compose.rb
lib/jekyll-compose/file_creator.rb
lib/jekyll-compose/file_editor.rb
lib/jekyll/commands/post.rb
spec/post_spec.rb

Every time when I generate a new post by `jekyll-compose` I need to find the new file in my editor, or copy-paste its path to open it.
Probably we can follow [migration_opener](https://github.com/evrone/migration_opener) approach and open file in selected editor automatically.

Auto open newly generated files in selected editor

---

lib/jekyll-compose/file_creator.rb
lib/jekyll-compose/file_mover.rb
spec/draft_spec.rb
spec/page_spec.rb
spec/post_spec.rb
spec/publish_spec.rb
spec/spec_helper.rb
spec/unpublish_spec.rb

(Other Rubocop failures, if any, will be handled by #68)

Replace `puts` calls with `Jekyll.logger.info`

---

.rubocop.yml
jekyll-compose.gemspec
lib/jekyll-compose.rb
lib/jekyll-compose/file_editor.rb
lib/jekyll-compose/movement_arg_parser.rb
lib/jekyll-compose/version.rb
lib/jekyll/commands/publish.rb
lib/jekyll/commands/unpublish.rb
spec/post_spec.rb

Rubocop 0.55

---

lib/jekyll-compose.rb
lib/jekyll/commands/post.rb
lib/jekyll/commands/publish.rb
spec/post_spec.rb
spec/publish_spec.rb

May make it easier to make changes to the format, i.e: to match the default format suggested
"YYYY-MM-DD HH:MM:SS +/-TTTT" as from https://jekyllrb.com/docs/frontmatter/
or to make these configurable values.

Formatting of dates and times in a DRY manner

---

lib/jekyll-compose/file_creator.rb
spec/draft_spec.rb
spec/page_spec.rb
spec/post_spec.rb

Mirroring the success message from `jekyll new` command to reduce visual noise.
I also removed the full-stop at the end to further reduce noise with short extensions e.g. **` at new-page.md.`**

Add some color to the success msg like jekyll new

---

lib/jekyll/commands/post.rb
spec/fixtures/_config.yml
spec/post_spec.rb

Currently, jekyll-compose `post` command generates only `layout` and `title` as front matter, but I'd like to add more front matters. For example:
``` yaml
---
layout: post
title: Blogging Like a Hacker
published: true
description: 
category: 
---
```
This PR adds feature that allows addtional front matter loaded from Jekyll's `_config.yml` for `jekyll post` command.
`_config.yml` sample is like:
``` yaml
jekyll_compose:
post_default_front_matter:
published: true
foo: bar
category: 
```

Allow additional front matter for Post

---

lib/jekyll/commands/draft.rb
spec/draft_spec.rb
spec/post_spec.rb

Adds two features to `draft` command:
- Define front matter defaults for new drafts using `jekyll_compose.draft_default_front_matter` in `_config.yml`
- Open new draft in editor based on `EDITOR`  OR `JEKYLL_EDITOR` ENV vars

Mirror `draft` command to current `post` command

---

lib/jekyll-compose/arg_parser.rb
lib/jekyll-compose/file_editor.rb
lib/jekyll/commands/draft.rb
lib/jekyll/commands/page.rb
lib/jekyll/commands/post.rb
lib/jekyll/commands/publish.rb
lib/jekyll/commands/unpublish.rb

* Every call to `Jekyll.configuration` outputs a `Configuration file: [file_path]` to the terminal. So, its better to generate the `config` hash from cli options once and pass that hash to subsequent steps
* Initialize `Compose::ArgParser` subclasses with both `cli options` and the `generated config` to keep the two concerns separate and avoid clobbering.
Resolves #73

Generate configuration from CLI options

---

.rubocop.yml
.travis.yml
Gemfile
appveyor.yml
jekyll-compose.gemspec

Targeting Ruby 2.4 does not change anything to the current codebase.

Drop support for Ruby 2.3

---

.rubocop.yml
.travis.yml
appveyor.yml
jekyll-compose.gemspec

The plugin doesn't use Ruby 2.4 specific syntax and therefore we can relax the Ruby version constraint to the minimum testable Ruby version across the ecosystem: Ruby 2.3
Other changes:
- Remove superfluous entries from the gemspec
- Test with Jekyll 4.0 pre-release

Re-introduce Ruby 2.3 support and test Jekyll 3.7+

---

lib/jekyll/commands/draft.rb
lib/jekyll/commands/page.rb
lib/jekyll/commands/post.rb
lib/jekyll/commands/publish.rb
lib/jekyll/commands/unpublish.rb

`jekyll post --help` shows both:
-s, --source SOURCE  Custom source directory
-s, --source [DIR]  Source directory (defaults to ./)

Removing source option for commands as it is appearing twice.

---

README.md
lib/jekyll-compose/file_editor.rb
spec/post_spec.rb

`JEKYLL_EDITOR` is the most specific and will still override `VISUAL` or `EDITOR`.
`VISUAL` will override `EDITOR` because apparently that's how bash works, and if this is unsatisfactory then setting `JEKYLL_EDITOR` will override both.

Include VISUAL as an editor option

---

.rubocop_todo.yml
README.md
lib/jekyll/commands/draft.rb
lib/jekyll/commands/post.rb
spec/draft_spec.rb
spec/post_spec.rb

This PR changes how default front matter is configured in preparation for user defined collections.
The previous structure for default front matter is:
```
jekyll_compose:
draft_default_front_matter:
description:
image:
category:
tags:
post_default_front_matter:
description:
image:
category:
tags:
published: false
sitemap: false
```
Instead of configuration keys of the form `post_default_front_matter` and `draft_default_front_matter`, which can only support default front matter only for posts and drafts, the new proposed structure is:
```
jekyll_compose:
default_front_matter:
drafts:
description:
image:
category:
tags:
posts:
description:
image:
category:
tags:
published: false
sitemap: false
```
This could allow for default front matter for user defined collections by configuring as …

Prepare for collections support with default front matter configuration

---

.rubocop_todo.yml
lib/jekyll-compose/file_info.rb
lib/jekyll/commands/draft.rb
lib/jekyll/commands/post.rb

- Centralizing logic to allow future changes to the *config dig sequence
(`"jekyll_compose"` => `"default_front_matter"` => `"posts" / "drafts" / "<collection>"`)* be made at a single place.
- Reduced line-lengths

Extract logic for computing default front matter

---

.rubocop_todo.yml
lib/jekyll/commands/draft.rb
lib/jekyll/commands/page.rb
lib/jekyll/commands/post.rb
lib/jekyll/commands/publish.rb
lib/jekyll/commands/unpublish.rb
spec/post_spec.rb

This is based off refactoring done by @ashmaroli for #103.

Refactoring to remove some rubocop warnings and for consistency

---

.rubocop_todo.yml
README.md
lib/jekyll-compose.rb
lib/jekyll/commands/compose.rb
spec/compose_spec.rb

This allows creating files in collections, including posts and drafts.
`jekyll compose "My New Post"`
`jekyll compose "My New Post" --post`
`jekyll compose "My new draft" --draft`
`jekyll compose "My New Thing" --collection "things"`
Default front matter can be specified for each collection.
```
jekyll_compose:
default_front_matter:
drafts:
layout: post
category:
tags:
posts:
published: false
sitemap: false
things:
layout: thing
```
Closes #84

Compose command for collections

---

README.md
lib/jekyll-compose.rb
lib/jekyll/commands/rename.rb
spec/rename_spec.rb

`jekyll rename _drafts/my-old-draft.md "My New Draft"` will
- move the draft to _drafts/my-new-draft.md
- set the yaml front matter title attribute to "My New Draft"
`jekyll rename _drafts/my-old-draft.md "My New Draft" --date "2012-03-04"` will
- move the draft to _drafts/my-new-draft.md
- set the yaml front matter title attribute to "My New Draft"
- set the yaml front matter date to 2012-03-04
`jekyll rename _posts/2001-02-03-my-old-post.md "My New Post"` will
- move the post to _posts/2001-02-03-my-new-post.md
- set the yaml front matter title attribute to "My New Post"
`jekyll rename _posts/2001-02-03-my-old-post.md "My New Post" --date "2012-03-04"` will
- move the post to _posts/2012-03-04-my-new-post.md
- set the yaml front matter title attribute to "My New Post"
- set the yaml …

Add rename command to change titles and filenames
